/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_BRICKBREAKER_PADDLE_PB_H_INCLUDED
#define PB_BRICKBREAKER_PADDLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _brickbreaker_PaddleIn_Buzz { 
    pb_callback_t motors;
    int32_t durationMillis;
} brickbreaker_PaddleIn_Buzz;

typedef struct _brickbreaker_PaddleOut { 
    double distance;
    bool buttonClicked;
} brickbreaker_PaddleOut;

typedef struct _brickbreaker_PaddleIn { 
    bool has_buzz;
    brickbreaker_PaddleIn_Buzz buzz;
} brickbreaker_PaddleIn;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define brickbreaker_PaddleOut_init_default      {0, 0}
#define brickbreaker_PaddleIn_init_default       {false, brickbreaker_PaddleIn_Buzz_init_default}
#define brickbreaker_PaddleIn_Buzz_init_default  {{{NULL}, NULL}, 0}
#define brickbreaker_PaddleOut_init_zero         {0, 0}
#define brickbreaker_PaddleIn_init_zero          {false, brickbreaker_PaddleIn_Buzz_init_zero}
#define brickbreaker_PaddleIn_Buzz_init_zero     {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define brickbreaker_PaddleIn_Buzz_motors_tag    1
#define brickbreaker_PaddleIn_Buzz_durationMillis_tag 2
#define brickbreaker_PaddleOut_distance_tag      1
#define brickbreaker_PaddleOut_buttonClicked_tag 2
#define brickbreaker_PaddleIn_buzz_tag           1

/* Struct field encoding specification for nanopb */
#define brickbreaker_PaddleOut_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   distance,          1) \
X(a, STATIC,   SINGULAR, BOOL,     buttonClicked,     2)
#define brickbreaker_PaddleOut_CALLBACK NULL
#define brickbreaker_PaddleOut_DEFAULT NULL

#define brickbreaker_PaddleIn_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  buzz,              1)
#define brickbreaker_PaddleIn_CALLBACK NULL
#define brickbreaker_PaddleIn_DEFAULT NULL
#define brickbreaker_PaddleIn_buzz_MSGTYPE brickbreaker_PaddleIn_Buzz

#define brickbreaker_PaddleIn_Buzz_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    motors,            1) \
X(a, STATIC,   SINGULAR, INT32,    durationMillis,    2)
#define brickbreaker_PaddleIn_Buzz_CALLBACK pb_default_field_callback
#define brickbreaker_PaddleIn_Buzz_DEFAULT NULL

extern const pb_msgdesc_t brickbreaker_PaddleOut_msg;
extern const pb_msgdesc_t brickbreaker_PaddleIn_msg;
extern const pb_msgdesc_t brickbreaker_PaddleIn_Buzz_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define brickbreaker_PaddleOut_fields &brickbreaker_PaddleOut_msg
#define brickbreaker_PaddleIn_fields &brickbreaker_PaddleIn_msg
#define brickbreaker_PaddleIn_Buzz_fields &brickbreaker_PaddleIn_Buzz_msg

/* Maximum encoded size of messages (where known) */
/* brickbreaker_PaddleIn_size depends on runtime parameters */
/* brickbreaker_PaddleIn_Buzz_size depends on runtime parameters */
#define brickbreaker_PaddleOut_size              11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
